parent=keycloak.v2
import=common/keycloak
styles=css/login.css
locales=vi,en
chargeopsTermsUrl=http://localhost:3000/dieu-khoan
chargeopsPrivacyUrl=http://localhost:3000/chinh-sach-bao-mat
chargeopsInlineConsentEnabled=true
